version: '3.8'
services:
  app:
    build:
      context: ./vote-api
      dockerfile: Dockerfile.Dockerfile
    ports:
      - "8080:8080"
    environment:
      PG_URL: postgres://user:password@database:5432/app_db
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: app_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"

  web-client:
    build:
      context: ./web-client
      dockerfile: web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      VOTE_API_BASE_URL: http://app:8080
    depends_on:
      - app

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/wal
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/log:/var/log
    command:
      - -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:9.5.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
