version: '3.8'

services:
  app:
    build:
      context: ./vote-api
      dockerfile: Dockerfile.Dockerfile
    ports:
      - "8081:8080"
    environment:
      PG_URL: postgres://user:password@staging-database:5432/app_db
    depends_on:
      - database
      - logstash

  database:
    image: postgres:14
    container_name: staging_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5433:5432" 

  web-client:
    build:
      context: ./web-client
      dockerfile: web.Dockerfile
    ports:
      - "3001:3000" 
    environment:
      VOTE_API_BASE_URL: http://app:8081 
    depends_on:
      - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch_staging
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash_staging
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5045:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana_staging
    depends_on:
      - elasticsearch
    ports:
      - "5602:5601"
