name: Go Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: vote-api

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23' 

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --enable-all --out-format=colored-line-number
        skip-pkg-cache: true 

    - name: Run golangci-lint
      run: golangci-lint run --timeout 5m

    - name: Check code formatting
      run: go fmt ./...

