name: Go API Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: vote-api

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Clean Golangci-Lint Cache
      run: sudo rm -rf ~/.cache/golangci-lint

    - name: Install dependencies
      run: go mod tidy

    - name: Linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --enable-all

    - name: Check Formatter
      run: go fmt ./...
