name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Install Yarn and dependencies
      run: |
        npm install -g yarn
        yarn install

    - name: Install Playwright
      run: npx playwright install

    - name: Run Playwright Tests
      run: yarn e2e
      env:
        VOTE_API_BASE_URL: http://localhost:8080
